name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ARM64

    steps:
    - uses: actions/checkout@v3
    
      
    - name: build docker and shell
      run: make docker-shell
      
    - run: make unit-test integration-test
    
    - run: make package release
